In [12]:
import numpy as np

In [3]:
#1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення
vector = np.arange(1,21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
#2 Створіть двовимірний масив (матрицю) розміром 4x4 заповніть його одиницями та виведіть значення
matrix = np.ones((4, 4), dtype=int)
print(matrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
#3 створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від -1 до 1 та виведіть його значення
matrix = np.random.randint(-1, 2, size=(5, 5))
print(matrix)

[[ 1  1  0 -1  0]
 [ 0 -1  1 -1  0]
 [ 1  0 -1 -1  0]
 [ 1  1  0 -1  0]
 [-1 -1  1 -1  0]]


In [14]:
#4 створіть масив розміром 3х3, заповніть його випадковими цілими числами в діапазоні від 0 до 1 та виведіть його значення
matrix = np.random.randint(2, size=(3, 3))
print(matrix)

[[1 1 1]
 [1 1 1]
 [0 0 1]]


In [15]:
#5 створіть два одновимірні масиви розміром 6, заповніть його випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення
vector_1 = np.array([np.random.randint(1, 21) for n in range(6)])
vector_2 = np.array([np.random.randint(1, 21) for n in range(6)])
print(vector_1 - vector_2)
print(vector_1 + vector_2)
print(vector_1 * vector_2)


[-11  10   5   6  -2  13]
[27 28 23  8 12 21]
[152 171 126   7  35  68]


In [17]:
#6 створіть дві матриці розміром 3х2 та 2х4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою
matrix_1 = np.random.randint(1, 6, size=(3, 2))
matrix_2 = np.random.randint(1, 6, size=(2, 4))
product = np.matmul(matrix_1, matrix_2)
print(product)

[[15 40 30 45]
 [15 40 30 45]
 [15 40 30 45]]


In [19]:
#7 створіть матрицю розміром 3х3 заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її 
matrix = np.array(np.random.randint(2, size=(3, 3)))
transp_matrix = np.transpose(matrix)
print(matrix)
print(transp_matrix)


[[0 0 0]
 [1 0 1]
 [0 0 0]]
[[0 1 0]
 [0 0 0]
 [0 1 0]]


In [20]:
 #8 створіть дві матиці розміром 3х3,заповніть їх випадковими дійсними числами в діапазоні від 1 до 10 та знайдіть їхню різницю 
matrix_1 = np.array(np.random.randint(1, 11,  size=(3, 3)))  
matrix_2 = np.array(np.random.randint(1, 11,  size=(3, 3)))  
print(matrix_1 - matrix_2)

[[-6  6  1]
 [ 7 -1  8]
 [ 0  1 -2]]


In [21]:
#9 створіть дві матиці розміром 3х3,заповніть їх випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть їх добуток
matrix_1 = np.array(np.random.randint(-5, 6,  size=(3, 3)))  
matrix_2 = np.array(np.random.randint(-5, 6,  size=(3, 3)))
product = np.matmul(matrix_1, matrix_2) 
print(product)

[[-20 -22   7]
 [  8  14 -13]
 [ -1  15  17]]


In [27]:
#10 створіть матрицю розміром 3х3 заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик що містить суму елементів кожного рядка матриці
matrix = np.array(np.random.uniform(-1, 1, 9)).reshape(3, 3)
vector = np.array([matrix[0].sum(), matrix[1].sum(), matrix[2].sum()])
r_vector = vector.reshape(3, 1)
print(r_vector)

[[-0.62336945]
 [ 0.65532684]
 [ 0.577956  ]]
